sudo: required
dist: xenial

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - lix run travix interp
